spring:
  #jackson响应配置
  jackson:
    default-property-inclusion: NON_NULL
    #响应时间-也可以使用注解在实体类上@JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
